/**
 * scienceTaxonomy — HexAstra Coach
 *
 * Taxonomie complète des sciences et sous-catégories.
 * Tous les keywords sont pré-normalisés : minuscules, sans accents.
 * Le détecteur normalise l'input avant matching — pas de doublon accent/non-accent ici.
 *
 * ~190 sous-catégories sur 6 sciences.
 */

// ── Types ──────────────────────────────────────────────────────────────────────

export type Science =
  | 'astro'
  | 'numerology'
  | 'human_design'
  | 'enneagram'
  | 'kua'
  | 'fusion'

export type UserIntent =
  | 'understand_self'
  | 'understand_period'
  | 'understand_relationship'
  | 'understand_block'
  | 'make_decision'
  | 'timing'
  | 'career_money'
  | 'health_energy'
  | 'spiritual_axis'
  | 'home_space'
  | 'direct_knowledge'
  | 'general'

export type ScienceSubCategory = {
  key: string
  science: Science
  label: string
  keywords: string[]
  aliases?: string[]
  intentHints?: UserIntent[]
  priority?: number
}

/** Alias de rétrocompatibilité — code existant importe SubCategory */
export type SubCategory = ScienceSubCategory

// ── Taxonomie ─────────────────────────────────────────────────────────────────

export const SCIENCE_TAXONOMY: ScienceSubCategory[] = [

  // ============================================================
  // ASTROLOGIE — NATALE
  // ============================================================

  {
    key: 'astro_natal_chart',
    science: 'astro',
    label: 'Thème natal complet',
    keywords: ['theme natal', 'carte du ciel', 'carte natale', 'thème natal', 'charte', 'charte astrale', 'theme astral', 'lecture de theme'],
    aliases: ['theme astral', 'carte astrale'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 90,
  },
  {
    key: 'astro_big3',
    science: 'astro',
    label: 'Big 3 — Soleil, Lune, Ascendant',
    keywords: ['big 3', 'big three', 'soleil lune ascendant', 'les trois', 'trio astro'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 85,
  },
  {
    key: 'astro_sign_sun',
    science: 'astro',
    label: 'Signe solaire',
    keywords: ['signe', 'signe solaire', 'soleil en', 'mon signe', 'signe du zodiaque', 'lion', 'vierge', 'balance', 'scorpion', 'sagittaire', 'capricorne', 'verseau', 'poissons', 'belier', 'taureau', 'gemeaux', 'cancer'],
    aliases: ['signe astrologique', 'signe de naissance'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 80,
  },
  {
    key: 'astro_sign_moon',
    science: 'astro',
    label: 'Signe lunaire',
    keywords: ['lune en', 'signe de lune', 'lune natale', 'ma lune', 'lune dans'],
    intentHints: ['understand_self', 'health_energy'],
    priority: 75,
  },
  {
    key: 'astro_sign_rising',
    science: 'astro',
    label: 'Ascendant',
    keywords: ['ascendant', 'asc', 'signe ascendant', 'mon ascendant'],
    aliases: ['asc'],
    intentHints: ['understand_self'],
    priority: 75,
  },
  {
    key: 'astro_planets_signs',
    science: 'astro',
    label: 'Planètes dans les signes',
    keywords: ['planete en', 'planetes dans', 'mercure en', 'venus en', 'mars en', 'jupiter en', 'saturne en', 'uranus en', 'neptune en', 'pluton en'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },
  {
    key: 'astro_planets_houses',
    science: 'astro',
    label: 'Planètes dans les maisons',
    keywords: ['planete en maison', 'saturne en maison', 'venus en maison', 'mars en maison', 'mercure en maison', 'planetes maisons'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },
  {
    key: 'astro_houses',
    science: 'astro',
    label: 'Maisons astrologiques',
    keywords: ['maison 1', 'maison 2', 'maison 3', 'maison 4', 'maison 5', 'maison 6', 'maison 7', 'maison 8', 'maison 9', 'maison 10', 'maison 11', 'maison 12', 'ma maison', 'les maisons', 'systeme de maison', 'cuspide'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 72,
  },
  {
    key: 'astro_house_1_to_12',
    science: 'astro',
    label: 'Maison 1 a 12',
    keywords: ['maison 1', 'maison 2', 'maison 3', 'maison 4', 'maison 5', 'maison 6', 'maison 7', 'maison 8', 'maison 9', 'maison 10', 'maison 11', 'maison 12', 'signification maison 7', 'sens maison 10', 'maison specifique astro'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 74,
  },
  {
    key: 'astro_aspects_major',
    science: 'astro',
    label: 'Aspects majeurs',
    keywords: ['aspect', 'carre', 'trigone', 'opposition', 'conjonction', 'sextile', 'aspects majeurs'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 65,
  },
  {
    key: 'astro_aspects_minor',
    science: 'astro',
    label: 'Aspects mineurs',
    keywords: ['aspects mineurs', 'quinconce', 'semi-carre', 'quintile', 'biquintile', 'sesquicarre'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 55,
  },
  {
    key: 'astro_elements',
    science: 'astro',
    label: 'Éléments — Feu, Terre, Air, Eau',
    keywords: ['element feu', 'element terre', 'element air', 'element eau', 'signes de feu', 'signes de terre', 'beaucoup de feu', 'beaucoup de terre'],
    intentHints: ['understand_self'],
    priority: 60,
  },
  {
    key: 'astro_modalities',
    science: 'astro',
    label: 'Modalités — Cardinal, Fixe, Mutable',
    keywords: ['cardinal', 'fixe', 'mutable', 'modalite', 'mode astrologique'],
    intentHints: ['understand_self'],
    priority: 55,
  },
  {
    key: 'astro_polarities',
    science: 'astro',
    label: 'Polarités Yin/Yang',
    keywords: ['polarite', 'yin yang astro', 'positif negatif astro'],
    intentHints: ['understand_self'],
    priority: 45,
  },
  {
    key: 'astro_rulerships',
    science: 'astro',
    label: 'Domiciles et maîtrises',
    keywords: ['maitrise', 'maitre de', 'planete maitresse', 'domicile planete', 'gouverneur'],
    intentHints: ['direct_knowledge'],
    priority: 50,
  },
  {
    key: 'astro_dignities',
    science: 'astro',
    label: 'Dignités planétaires',
    keywords: ['dignite', 'en domicile', 'en exaltation', 'en exil', 'en chute', 'planete exaltee', 'planete en chute', 'planete en detriment', 'planete faible', 'planete forte'],
    aliases: ['planete exilee', 'planete en exil'],
    intentHints: ['direct_knowledge', 'understand_self'],
    priority: 60,
  },
  {
    key: 'astro_exaltation',
    science: 'astro',
    label: 'Exaltation planetaire',
    keywords: ['en exaltation', 'planete exaltee', 'signe d exaltation', 'exaltation planetaire'],
    intentHints: ['direct_knowledge', 'understand_self'],
    priority: 58,
  },
  {
    key: 'astro_detriment',
    science: 'astro',
    label: 'Detriment / exil',
    keywords: ['en detriment', 'en exil', 'planete en exil', 'planete en detriment', 'planete exilee'],
    intentHints: ['direct_knowledge', 'understand_self'],
    priority: 58,
  },
  {
    key: 'astro_fall',
    science: 'astro',
    label: 'Chute planetaire',
    keywords: ['en chute', 'planete en chute', 'signe de chute', 'chute planetaire'],
    intentHints: ['direct_knowledge', 'understand_self'],
    priority: 58,
  },
  {
    key: 'astro_retrograde_natal',
    science: 'astro',
    label: 'Rétrogrades natales',
    keywords: ['retrograde natal', 'planete retro naissance', 'mercure retro natal', 'saturne retro natal'],
    intentHints: ['understand_self'],
    priority: 55,
  },
  {
    key: 'astro_stellium',
    science: 'astro',
    label: 'Stellium',
    keywords: ['stellium', 'concentration de planetes', 'plusieurs planetes en', 'amas planétaire'],
    intentHints: ['understand_self'],
    priority: 60,
  },
  {
    key: 'astro_dominants',
    science: 'astro',
    label: 'Dominantes astrologiques',
    keywords: ['dominant', 'planete dominante', 'signe dominant', 'element dominant'],
    intentHints: ['understand_self'],
    priority: 65,
  },
  {
    key: 'astro_lunar_nodes',
    science: 'astro',
    label: 'Nœuds lunaires',
    keywords: ['noeud lunaire', 'noeud nord', 'noeud sud', 'dragon', 'queue du dragon', 'tete du dragon', 'axe nodal'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 70,
  },
  {
    key: 'astro_chiron',
    science: 'astro',
    label: 'Chiron — La blessure',
    keywords: ['chiron', 'blessure karmique astro', 'plaie chiron'],
    intentHints: ['understand_self', 'spiritual_axis', 'understand_block'],
    priority: 65,
  },
  {
    key: 'astro_lilith',
    science: 'astro',
    label: 'Lilith',
    keywords: ['lilith', 'lune noire', 'lilith en'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 60,
  },
  {
    key: 'astro_part_of_fortune',
    science: 'astro',
    label: 'Part of Fortune',
    keywords: ['part de fortune', 'lot de fortune', 'fortune', 'point arabe'],
    intentHints: ['understand_self', 'career_money'],
    priority: 55,
  },
  {
    key: 'astro_vertex',
    science: 'astro',
    label: 'Vertex',
    keywords: ['vertex', 'anti-vertex'],
    intentHints: ['understand_self', 'understand_relationship'],
    priority: 45,
  },
  {
    key: 'astro_mc_ic_desc_asc',
    science: 'astro',
    label: 'Angles — MC, IC, DSC, ASC',
    keywords: ['milieu du ciel', 'mc', 'fond du ciel', 'ic', 'descendant', 'dsc', 'angles astro', 'axe mc-ic', 'axe asc-dsc'],
    intentHints: ['understand_self', 'career_money'],
    priority: 68,
  },
  {
    key: 'astro_yod',
    science: 'astro',
    label: 'Yod — Doigt de Dieu',
    keywords: ['yod', 'doigt de dieu', 'configuration yod'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 55,
  },
  {
    key: 'astro_tsquare',
    science: 'astro',
    label: 'T-Carré',
    keywords: ['t-carre', 't carre', 'configuration t', 'grand carre', 'carre en t'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 55,
  },
  {
    key: 'astro_grand_trine',
    science: 'astro',
    label: 'Grand Trine',
    keywords: ['grand trine', 'grand trigone', 'triangle de feu', 'triangle de terre', 'triangle d eau', 'triangle d air'],
    intentHints: ['understand_self'],
    priority: 55,
  },
  {
    key: 'astro_kite',
    science: 'astro',
    label: 'Kite — Cerf-Volant',
    keywords: ['kite astro', 'cerf-volant astro', 'configuration kite'],
    intentHints: ['understand_self'],
    priority: 45,
  },
  {
    key: 'astro_mystic_rectangle',
    science: 'astro',
    label: 'Rectangle mystique',
    keywords: ['rectangle mystique', 'mystic rectangle'],
    intentHints: ['understand_self'],
    priority: 45,
  },

  // ── TRANSITS / TEMPS RÉEL ──────────────────────────────────────────────────

  {
    key: 'astro_transits_current',
    science: 'astro',
    label: 'Transits actuels',
    keywords: ['transit', 'transits', 'transit actuel', 'transits actuels', 'energie actuelle', 'ce que je traverse', 'mes transits', 'energie du moment', 'periode actuelle', 'transits du moment', 'en ce moment astro', 'cycles en cours'],
    aliases: ['transits du moment'],
    intentHints: ['understand_period', 'timing'],
    priority: 95,
  },
  {
    key: 'astro_transits_love',
    science: 'astro',
    label: 'Transits amour / relation',
    keywords: ['transits amour', 'transits relation', 'venus transit', 'transits en maison 7', 'transits couple', 'transits sentimentaux'],
    intentHints: ['understand_relationship', 'timing'],
    priority: 80,
  },
  {
    key: 'astro_transits_work',
    science: 'astro',
    label: 'Transits travail / carrière',
    keywords: ['transits travail', 'transits carriere', 'transits pro', 'saturne transit', 'jupiter transit carriere', 'transits en maison 10'],
    intentHints: ['career_money', 'timing'],
    priority: 80,
  },
  {
    key: 'astro_transits_money',
    science: 'astro',
    label: 'Transits argent / finances',
    keywords: ['transits argent', 'transits finances', 'jupiter transit argent', 'transits en maison 2', 'transits en maison 8'],
    intentHints: ['career_money', 'timing'],
    priority: 75,
  },
  {
    key: 'astro_transits_energy',
    science: 'astro',
    label: 'Transits énergie / santé',
    keywords: ['transits energie', 'transits sante', 'transits vitalite', 'mars transit', 'soleil transit'],
    intentHints: ['health_energy', 'timing'],
    priority: 75,
  },
  {
    key: 'astro_transits_relationships',
    science: 'astro',
    label: 'Transits relations (large)',
    keywords: ['transits relations', 'transits famille', 'transits amis', 'transits social'],
    intentHints: ['understand_relationship', 'timing'],
    priority: 70,
  },
  {
    key: 'astro_transits_timing',
    science: 'astro',
    label: 'Timing astrologique',
    keywords: ['bon moment astro', 'timing astrologique', 'quand agir selon astro', 'fenetre astrologique', 'moment favorable astro'],
    intentHints: ['timing', 'make_decision'],
    priority: 88,
  },
  {
    key: 'astro_retrogrades_current',
    science: 'astro',
    label: 'Rétrogrades en cours',
    keywords: ['retrograde en cours', 'retrograde actuel', 'mercure retro', 'venus retro', 'mars retro', 'saturne retro', 'planete retro en ce moment'],
    intentHints: ['understand_period', 'timing'],
    priority: 78,
  },
  {
    key: 'astro_eclipses',
    science: 'astro',
    label: 'Éclipses',
    keywords: ['eclipse', 'eclipses', 'eclipse solaire', 'eclipse lunaire', 'effet eclipse', 'saison des eclipses'],
    intentHints: ['understand_period', 'timing'],
    priority: 78,
  },
  {
    key: 'astro_new_moon',
    science: 'astro',
    label: 'Nouvelle lune',
    keywords: ['nouvelle lune', 'novilune', 'lune noire', 'debut de cycle lunaire'],
    intentHints: ['timing', 'understand_period'],
    priority: 72,
  },
  {
    key: 'astro_full_moon',
    science: 'astro',
    label: 'Pleine lune',
    keywords: ['pleine lune', 'plenilune', 'energie pleine lune', 'revelations'],
    intentHints: ['timing', 'understand_period'],
    priority: 72,
  },
  {
    key: 'astro_ingresses',
    science: 'astro',
    label: 'Ingresses planétaires',
    keywords: ['ingresse', 'planete entre en', 'saturne entre en', 'jupiter entre en', 'changement de signe planete'],
    intentHints: ['understand_period'],
    priority: 65,
  },
  {
    key: 'astro_saturn_return',
    science: 'astro',
    label: 'Retour de Saturne',
    keywords: ['retour de saturne', 'retour saturne', 'saturn return', 'mes 29 ans', 'mes 30 ans', 'mes 58 ans', 'passage saturne'],
    intentHints: ['understand_period', 'understand_self', 'timing'],
    priority: 85,
  },
  {
    key: 'astro_jupiter_return',
    science: 'astro',
    label: 'Retour de Jupiter',
    keywords: ['retour de jupiter', 'retour jupiter', 'jupiter return', 'cycle jupiter'],
    intentHints: ['understand_period', 'timing'],
    priority: 70,
  },
  {
    key: 'astro_nodal_return',
    science: 'astro',
    label: 'Retour nodal',
    keywords: ['retour nodal', 'nodal return', 'cycle nodal', 'revolution nodale'],
    intentHints: ['understand_period', 'spiritual_axis'],
    priority: 65,
  },
  {
    key: 'astro_uranus_opposition',
    science: 'astro',
    label: 'Opposition Uranus',
    keywords: ['opposition uranus', 'uranus opposition', 'crise de la quarantaine astro', 'mes 40 ans astro'],
    intentHints: ['understand_period', 'understand_self'],
    priority: 65,
  },
  {
    key: 'astro_midlife_transits',
    science: 'astro',
    label: 'Transits mi-vie',
    keywords: ['mi-vie astro', 'crise mi-vie', 'milieu de vie astro', 'grands transits', 'transits importants'],
    intentHints: ['understand_period', 'understand_self'],
    priority: 70,
  },

  // ── PRÉVISIONNEL / CYCLES ──────────────────────────────────────────────────

  {
    key: 'astro_progressions',
    science: 'astro',
    label: 'Progressions',
    keywords: ['progression', 'progressions', 'carte progressive'],
    intentHints: ['understand_period', 'timing'],
    priority: 70,
  },
  {
    key: 'astro_secondary_progressions',
    science: 'astro',
    label: 'Progressions secondaires',
    keywords: ['progression secondaire', 'progressions secondaires', 'lune progressee', 'soleil progresse'],
    intentHints: ['understand_period', 'timing'],
    priority: 68,
  },
  {
    key: 'astro_solar_arc',
    science: 'astro',
    label: 'Arc solaire',
    keywords: ['arc solaire', 'direction arc solaire', 'solar arc'],
    intentHints: ['understand_period', 'timing'],
    priority: 65,
  },
  {
    key: 'astro_solar_return',
    science: 'astro',
    label: 'Retour solaire',
    keywords: ['retour solaire', 'solar return', 'theme annuel', 'anniversaire astro', 'revolution solaire'],
    intentHints: ['understand_period', 'timing'],
    priority: 80,
  },
  {
    key: 'astro_lunar_return',
    science: 'astro',
    label: 'Retour lunaire',
    keywords: ['retour lunaire', 'lunar return', 'cycle mensuel astro', 'theme mensuel'],
    intentHints: ['understand_period', 'timing'],
    priority: 68,
  },
  {
    key: 'astro_annual_themes',
    science: 'astro',
    label: 'Thèmes annuels',
    keywords: ['annee astrologique', 'themes annuels', 'cette annee astro', 'mon annee astro', 'bilan astro'],
    intentHints: ['understand_period'],
    priority: 75,
  },
  {
    key: 'astro_monthly_cycles',
    science: 'astro',
    label: 'Cycles mensuels',
    keywords: ['mois astro', 'ce mois astro', 'energie du mois', 'cycle mensuel'],
    intentHints: ['understand_period', 'timing'],
    priority: 68,
  },

  // ── RELATIONNEL ───────────────────────────────────────────────────────────

  {
    key: 'astro_synastry',
    science: 'astro',
    label: 'Synastrie',
    keywords: ['synastrie', 'compatibilite astrologique', 'compatibilite astro', 'relation astrologique', 'nos themes', 'themes croises', 'aspects en synastrie'],
    intentHints: ['understand_relationship'],
    priority: 88,
  },
  {
    key: 'astro_composite',
    science: 'astro',
    label: 'Composite',
    keywords: ['composite', 'theme composite', 'carte composite', 'theme du couple'],
    intentHints: ['understand_relationship'],
    priority: 75,
  },
  {
    key: 'astro_relationship_dynamics',
    science: 'astro',
    label: 'Dynamiques relationnelles astro',
    keywords: ['dynamique relationnelle astro', 'tension astro', 'compatibilite signes', 'quel signe va avec'],
    intentHints: ['understand_relationship'],
    priority: 72,
  },

  // ── SPATIAL / GÉO ──────────────────────────────────────────────────────────

  {
    key: 'astro_astrocartography',
    science: 'astro',
    label: 'Astrocartographie',
    keywords: ['astrocartographie', 'astrocarto', 'carte de la planete astro', 'ou vivre selon astro', 'ou vivre selon mon astro', 'ou demenager astro', 'lignes astro', 'voyage astro'],
    intentHints: ['home_space', 'understand_self'],
    priority: 80,
  },
  {
    key: 'astro_relocation',
    science: 'astro',
    label: 'Relocation astrale',
    keywords: ['relocation', 'theme de relocation', 'relocalisation', 'demenagement astro'],
    intentHints: ['home_space'],
    priority: 70,
  },
  {
    key: 'astro_geo_astrology',
    science: 'astro',
    label: 'Géo-astrologie',
    keywords: ['geo-astrologie', 'geo astrologie', 'astrologie geographique'],
    intentHints: ['home_space'],
    priority: 65,
  },

  // ── SPIRITUEL / APPROFONDI ────────────────────────────────────────────────

  {
    key: 'astro_karmic',
    science: 'astro',
    label: 'Astrologie karmique',
    keywords: ['astrologie karmique', 'karma astro', 'dette karmique astro', 'passé vies astro'],
    intentHints: ['spiritual_axis', 'understand_self'],
    priority: 70,
  },
  {
    key: 'astro_evolutionary',
    science: 'astro',
    label: 'Astrologie évolutive',
    keywords: ['astrologie evolutive', 'astrologie de l ame', 'evolution spirituelle astro'],
    intentHints: ['spiritual_axis'],
    priority: 68,
  },
  {
    key: 'astro_esoteric',
    science: 'astro',
    label: 'Astrologie ésotérique',
    keywords: ['astrologie esoterique', 'esoterique astro', 'astrologie avancee'],
    intentHints: ['spiritual_axis'],
    priority: 60,
  },
  {
    key: 'astro_soul_path',
    science: 'astro',
    label: 'Chemin d\'âme',
    keywords: ['chemin d ame astro', 'mission de l ame', 'but de l ame', 'but astro', 'vocation astro'],
    intentHints: ['spiritual_axis', 'understand_self'],
    priority: 70,
  },

  // ============================================================
  // NUMÉROLOGIE
  // ============================================================

  // ── FONDATIONS ────────────────────────────────────────────────────────────

  {
    key: 'num_core_profile',
    science: 'numerology',
    label: 'Profil numérologique complet',
    keywords: ['profil numerologique', 'lecture numerologie', 'ma numerologie', 'mon profil numerique'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 90,
  },
  {
    key: 'num_life_path',
    science: 'numerology',
    label: 'Chemin de vie',
    keywords: ['chemin de vie', 'cdv', 'mon chemin', 'numero de chemin de vie', 'chemin de vie 1', 'chemin de vie 2', 'chemin de vie 3', 'chemin de vie 4', 'chemin de vie 5', 'chemin de vie 6', 'chemin de vie 7', 'chemin de vie 8', 'chemin de vie 9', 'chemin de vie 11', 'chemin de vie 22', 'chemin de vie 33'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 95,
  },
  {
    key: 'num_expression',
    science: 'numerology',
    label: 'Nombre d\'expression',
    keywords: ['nombre d expression', 'nombre expression', 'numero d expression', 'vibration du nom', 'expression numerologique'],
    intentHints: ['understand_self'],
    priority: 80,
  },
  {
    key: 'num_soul_urge',
    science: 'numerology',
    label: 'Désir de l\'âme (motivation intime)',
    keywords: ['desir de l ame', 'nombre d ame', 'numero de l ame', 'vibration interieure', 'motivation profonde numerologie'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 78,
  },
  {
    key: 'num_personality',
    science: 'numerology',
    label: 'Nombre de personnalité',
    keywords: ['nombre de personnalite', 'numero de personnalite', 'image exterieure numerologie'],
    intentHints: ['understand_self'],
    priority: 72,
  },
  {
    key: 'num_birthday_number',
    science: 'numerology',
    label: 'Nombre du jour de naissance',
    keywords: ['nombre du jour', 'jour de naissance numerologie', 'don naturel numerologie'],
    intentHints: ['understand_self'],
    priority: 68,
  },
  {
    key: 'num_maturity_number',
    science: 'numerology',
    label: 'Nombre de maturité',
    keywords: ['nombre de maturite', 'numerologie maturite', 'numero de maturite'],
    intentHints: ['understand_self'],
    priority: 65,
  },
  {
    key: 'num_attitude_number',
    science: 'numerology',
    label: 'Nombre d\'attitude',
    keywords: ['nombre d attitude', 'numero d attitude', 'attitude numerologie'],
    intentHints: ['understand_self'],
    priority: 60,
  },
  {
    key: 'num_balance_number',
    science: 'numerology',
    label: 'Nombre d\'équilibre',
    keywords: ['nombre d equilibre', 'numero d equilibre', 'equilibre numerologie'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 58,
  },
  {
    key: 'num_rational_thought',
    science: 'numerology',
    label: 'Pensée rationnelle',
    keywords: ['pensee rationnelle', 'numero rationnel', 'mental numerologie'],
    intentHints: ['understand_self'],
    priority: 55,
  },
  {
    key: 'num_subconscious_self',
    science: 'numerology',
    label: 'Soi subconscient',
    keywords: ['soi subconscient', 'numerologie inconscient', 'subconscient numerologie'],
    intentHints: ['understand_self'],
    priority: 55,
  },
  {
    key: 'num_karmic_lessons',
    science: 'numerology',
    label: 'Leçons karmiques',
    keywords: ['lecons karmiques', 'numeros manquants', 'karme numerologie', 'lacunes numerologie'],
    intentHints: ['understand_self', 'spiritual_axis', 'understand_block'],
    priority: 70,
  },
  {
    key: 'num_karmic_debt',
    science: 'numerology',
    label: 'Dettes karmiques',
    keywords: ['dette karmique', 'dettes karmiques', '13', '14', '16', '19', 'nombre karmique', 'karma numerologie'],
    intentHints: ['understand_self', 'spiritual_axis', 'understand_block'],
    priority: 75,
  },
  {
    key: 'num_hidden_passion',
    science: 'numerology',
    label: 'Passion cachée',
    keywords: ['passion cachee', 'nombre passion', 'passion dominante numerologie'],
    intentHints: ['understand_self'],
    priority: 60,
  },
  {
    key: 'num_planes_of_expression',
    science: 'numerology',
    label: 'Plans d\'expression',
    keywords: ['plan physique', 'plan mental', 'plan emotionnel', 'plan intuitif', 'plans d expression'],
    intentHints: ['understand_self'],
    priority: 58,
  },
  {
    key: 'num_cornerstone_capstone',
    science: 'numerology',
    label: 'Pierre angulaire et clé de voûte',
    keywords: ['pierre angulaire', 'cle de voute', 'cornerstone', 'capstone', 'premiere lettre', 'derniere lettre'],
    intentHints: ['understand_self'],
    priority: 55,
  },
  {
    key: 'num_first_vowel',
    science: 'numerology',
    label: 'Première voyelle',
    keywords: ['premiere voyelle', 'premiere lettre voyelle'],
    intentHints: ['understand_self'],
    priority: 50,
  },
  {
    key: 'num_first_consonant',
    science: 'numerology',
    label: 'Premiere consonne',
    keywords: ['premiere consonne', 'premiere lettre consonne'],
    intentHints: ['understand_self'],
    priority: 50,
  },

  // ── CYCLES / TEMPS ────────────────────────────────────────────────────────

  {
    key: 'num_personal_year',
    science: 'numerology',
    label: 'Année personnelle',
    keywords: ['annee personnelle', 'annee perso', 'annee perso 2025', 'annee perso 2026', 'mon annee', 'cycle annuel numerologie', 'annee 1', 'annee 2', 'annee 3', 'annee 4', 'annee 5', 'annee 6', 'annee 7', 'annee 8', 'annee 9'],
    intentHints: ['understand_period', 'timing'],
    priority: 95,
  },
  {
    key: 'num_personal_month',
    science: 'numerology',
    label: 'Mois personnel',
    keywords: ['mois personnel', 'mois perso', 'cycle mensuel numerologie', 'mon mois'],
    intentHints: ['understand_period', 'timing'],
    priority: 88,
  },
  {
    key: 'num_personal_day',
    science: 'numerology',
    label: 'Jour personnel',
    keywords: ['jour personnel', 'jour perso', 'energie du jour numerologie', 'mon jour'],
    intentHints: ['timing'],
    priority: 78,
  },
  {
    key: 'num_pinnacles',
    science: 'numerology',
    label: 'Sommets (Pinnacles)',
    keywords: ['sommet', 'sommets numerologie', 'pinnacle', 'pinnacles', 'grandes etapes numerologie'],
    intentHints: ['understand_period', 'understand_self'],
    priority: 70,
  },
  {
    key: 'num_challenges',
    science: 'numerology',
    label: 'Défis numériques',
    keywords: ['defi numerologique', 'defis', 'epreuves numerologie', 'obstacle numerologie'],
    intentHints: ['understand_block', 'understand_self'],
    priority: 70,
  },
  {
    key: 'num_essence',
    science: 'numerology',
    label: 'Essence (transit de nom)',
    keywords: ['essence numerologie', 'nombre essence', 'transit de nom'],
    intentHints: ['understand_period'],
    priority: 62,
  },
  {
    key: 'num_transits',
    science: 'numerology',
    label: 'Transits numériques',
    keywords: ['transits numerologie', 'transit numerologique', 'cycle de transit'],
    intentHints: ['understand_period'],
    priority: 65,
  },
  {
    key: 'num_period_cycles',
    science: 'numerology',
    label: 'Cycles de vie',
    keywords: ['cycles de vie', 'grandes periodes', 'periode de vie numerologie'],
    intentHints: ['understand_period'],
    priority: 65,
  },

  // ── RELATIONNEL / COMPATIBILITÉ ──────────────────────────────────────────

  {
    key: 'num_relationship_compatibility',
    science: 'numerology',
    label: 'Compatibilité numérique',
    keywords: ['compatibilite numerologique', 'compatibilite numerique', 'numerologie couple', 'calcul couple'],
    intentHints: ['understand_relationship'],
    priority: 78,
  },
  {
    key: 'num_couple_dynamics',
    science: 'numerology',
    label: 'Dynamiques de couple',
    keywords: ['dynamique couple numerologie', 'relation numerologique', 'tension couple chiffres'],
    intentHints: ['understand_relationship'],
    priority: 70,
  },
  {
    key: 'num_name_compatibility',
    science: 'numerology',
    label: 'Compatibilité de noms',
    keywords: ['compatibilite de noms', 'vibration commune', 'noms compatibles'],
    intentHints: ['understand_relationship'],
    priority: 60,
  },

  // ── NOMS / IDENTITÉ ───────────────────────────────────────────────────────

  {
    key: 'num_name_analysis',
    science: 'numerology',
    label: 'Analyse du prénom',
    keywords: ['analyse du prenom', 'vibration du prenom', 'numerologie du prenom', 'mon prenom', 'que signifie mon prenom'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 80,
  },
  {
    key: 'num_business_name',
    science: 'numerology',
    label: 'Nom d\'entreprise',
    keywords: ['nom d entreprise', 'numerologie entreprise', 'choisir nom entreprise', 'vibration marque'],
    intentHints: ['career_money', 'direct_knowledge'],
    priority: 72,
  },
  {
    key: 'num_brand_name',
    science: 'numerology',
    label: 'Nom de marque',
    keywords: ['nom de marque', 'marque numerologie', 'vibration nom marque'],
    intentHints: ['career_money'],
    priority: 65,
  },
  {
    key: 'num_name_change',
    science: 'numerology',
    label: 'Changement de prénom / nom',
    keywords: ['changer de prenom', 'changer de nom', 'changement de nom', 'prenom de scene', 'pseudonyme numerologie'],
    intentHints: ['understand_self', 'make_decision'],
    priority: 70,
  },
  {
    key: 'num_signature_vibration',
    science: 'numerology',
    label: 'Vibration de la signature',
    keywords: ['signature', 'vibration de la signature', 'numerologie signature'],
    intentHints: ['understand_self'],
    priority: 55,
  },

  // ── SPATIAL ───────────────────────────────────────────────────────────────

  {
    key: 'num_house_number',
    science: 'numerology',
    label: 'Numéro de maison',
    keywords: ['numero de maison', 'maison numero', 'vibration de la maison', 'numerologie adresse', 'numerologie maison'],
    intentHints: ['home_space'],
    priority: 78,
  },
  {
    key: 'num_address_vibration',
    science: 'numerology',
    label: 'Vibration de l\'adresse',
    keywords: ['adresse numerologie', 'vibration adresse', 'mon adresse en numerologie'],
    intentHints: ['home_space'],
    priority: 72,
  },
  {
    key: 'num_geo_numerology',
    science: 'numerology',
    label: 'Géo-numérologie',
    keywords: ['geo-numerologie', 'geo numerologie', 'numerologie geographique', 'pays numerologie'],
    intentHints: ['home_space'],
    priority: 60,
  },

  // ── MATÉRIEL / PRO ────────────────────────────────────────────────────────

  {
    key: 'num_career_axis',
    science: 'numerology',
    label: 'Axe carrière',
    keywords: ['carriere numerologie', 'vocation numerologique', 'metier numerologie', 'travail numerologie'],
    intentHints: ['career_money'],
    priority: 75,
  },
  {
    key: 'num_money_axis',
    science: 'numerology',
    label: 'Axe argent / finances',
    keywords: ['argent numerologie', 'finances numerologie', 'numerologie richesse', 'chemin financier'],
    intentHints: ['career_money'],
    priority: 72,
  },
  {
    key: 'num_decision_timing',
    science: 'numerology',
    label: 'Timing décision (numéro)',
    keywords: ['bon moment numerologie', 'quand agir numerologie', 'timing numerologique', 'decision numerologie'],
    intentHints: ['timing', 'make_decision'],
    priority: 80,
  },

  // ── SPIRITUEL ─────────────────────────────────────────────────────────────

  {
    key: 'num_master_numbers',
    science: 'numerology',
    label: 'Nombres maîtres',
    keywords: ['nombre maitre', 'nombres maitres', '11', '22', '33', 'numero 11', 'numero 22', 'numero 33'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 78,
  },
  {
    key: 'num_repeating_numbers',
    science: 'numerology',
    label: 'Nombres répétitifs / synchros',
    keywords: ['heure miroir', '111', '222', '333', '444', '555', '666', '777', '888', '999', '1111', 'synchronicite', 'chiffres qui repetent', 'je vois souvent'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 80,
  },
  {
    key: 'num_spiritual_lessons',
    science: 'numerology',
    label: 'Leçons spirituelles',
    keywords: ['lecons spirituelles numerologie', 'apprentissage vie numerologie', 'mission spirituelle'],
    intentHints: ['spiritual_axis'],
    priority: 65,
  },
  {
    key: 'num_soul_mission',
    science: 'numerology',
    label: 'Mission de l\'âme',
    keywords: ['mission de l ame', 'mission numerologie', 'but de vie', 'vocation profonde'],
    intentHints: ['spiritual_axis', 'understand_self'],
    priority: 72,
  },

  // ============================================================
  // HUMAN DESIGN
  // ============================================================

  // ── FONDATIONS ────────────────────────────────────────────────────────────

  {
    key: 'hd_full_chart',
    science: 'human_design',
    label: 'Bodygraph complet',
    keywords: ['bodygraph', 'carte hd', 'mon chart hd', 'lecture hd', 'human design complet', 'mon human design'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 90,
  },
  {
    key: 'hd_type',
    science: 'human_design',
    label: 'Type HD',
    keywords: ['type hd', 'mon type', 'generateur', 'generateur pur', 'generateur manifestant', 'projecteur', 'manifesteur', 'reflecteur', 'quel type suis-je', 'type en hd'],
    intentHints: ['understand_self'],
    priority: 95,
  },
  {
    key: 'hd_strategy',
    science: 'human_design',
    label: 'Stratégie HD',
    keywords: ['strategie hd', 'ma strategie', 'attendre pour repondre', 'attendre l invitation', 'initier', 'attendre le cycle lunaire', 'strategy hd'],
    intentHints: ['make_decision', 'understand_self'],
    priority: 90,
  },
  {
    key: 'hd_authority',
    science: 'human_design',
    label: 'Autorité HD',
    keywords: ['autorite hd', 'mon autorite', 'autorite sacrale', 'autorite emotionnelle', 'autorite splénique', 'autorite ego', 'autorite soi', 'autorite mentale', 'pas d autorite', 'comment decider hd'],
    aliases: ['autorite'],
    intentHints: ['make_decision', 'understand_self'],
    priority: 92,
  },
  {
    key: 'hd_profile',
    science: 'human_design',
    label: 'Profil HD',
    keywords: ['profil hd', 'mon profil', 'profil 1-3', 'profil 2-4', 'profil 3-5', 'profil 4-6', 'profil 5-1', 'profil 6-2', 'lignes du profil'],
    intentHints: ['understand_self'],
    priority: 85,
  },
  {
    key: 'hd_definition',
    science: 'human_design',
    label: 'Définition HD',
    keywords: ['definition hd', 'definition simple', 'definition double', 'definition triple', 'definition quadruple', 'split', 'split double'],
    intentHints: ['understand_self'],
    priority: 78,
  },
  {
    key: 'hd_signature_notself',
    science: 'human_design',
    label: 'Signature et Thème du Non-Soi',
    keywords: ['signature hd', 'theme du non soi', 'not self', 'frustration hd', 'colere hd', 'amertume hd', 'desespoir hd', 'satisfaction hd', 'succes hd', 'paix hd'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 85,
  },
  {
    key: 'hd_incarnation_cross',
    science: 'human_design',
    label: 'Croix d\'incarnation',
    keywords: ['croix d incarnation', 'croix incarnation', 'incarnation cross', 'ma croix hd', 'mission hd'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 88,
  },

  // ── CENTRES ───────────────────────────────────────────────────────────────

  {
    key: 'hd_centers_overview',
    science: 'human_design',
    label: 'Centres HD — vue d\'ensemble',
    keywords: ['centres hd', 'mes centres', 'centres definis', 'centres ouverts', 'centres non definis'],
    intentHints: ['understand_self'],
    priority: 82,
  },
  {
    key: 'hd_defined_centers',
    science: 'human_design',
    label: 'Centres définis',
    keywords: ['centres definis hd', 'centre define', 'centres actifs hd'],
    intentHints: ['understand_self'],
    priority: 72,
  },
  {
    key: 'hd_undefined_centers',
    science: 'human_design',
    label: 'Centres non définis / ouverts',
    keywords: ['centres non definis', 'centres ouverts hd', 'open centers', 'centre blanc hd'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 72,
  },
  {
    key: 'hd_open_centers',
    science: 'human_design',
    label: 'Centres ouverts',
    keywords: ['centre ouvert', 'centres ouverts', 'open center', 'open centers', 'centre completement ouvert'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 70,
  },
  {
    key: 'hd_head_center',
    science: 'human_design',
    label: 'Centre Tête',
    keywords: ['centre tete hd', 'centre couronne', 'centre de la tete'],
    intentHints: ['understand_self'],
    priority: 62,
  },
  {
    key: 'hd_ajna_center',
    science: 'human_design',
    label: 'Centre Ajna',
    keywords: ['centre ajna', 'ajna hd', 'centre mental'],
    intentHints: ['understand_self'],
    priority: 62,
  },
  {
    key: 'hd_throat_center',
    science: 'human_design',
    label: 'Centre Gorge',
    keywords: ['centre gorge', 'gorge hd', 'throat center', 'expression hd'],
    intentHints: ['understand_self'],
    priority: 62,
  },
  {
    key: 'hd_g_center',
    science: 'human_design',
    label: 'Centre G (Identité)',
    keywords: ['centre g hd', 'g center', 'centre identite', 'centre de l identite', 'centre ji'],
    intentHints: ['understand_self'],
    priority: 65,
  },
  {
    key: 'hd_ego_center',
    science: 'human_design',
    label: 'Centre Ego / Cœur',
    keywords: ['centre ego hd', 'ego center', 'centre du coeur', 'willpower hd'],
    intentHints: ['understand_self'],
    priority: 62,
  },
  {
    key: 'hd_solar_plexus',
    science: 'human_design',
    label: 'Centre Plexus Solaire (émotions)',
    keywords: ['plexus solaire hd', 'solar plexus hd', 'centre emotionnel hd', 'emotions hd', 'vague emotionnelle'],
    intentHints: ['understand_self', 'health_energy'],
    priority: 70,
  },
  {
    key: 'hd_sacral_center',
    science: 'human_design',
    label: 'Centre Sacral',
    keywords: ['centre sacral', 'sacral hd', 'sacral center', 'reponse sacrale', 'energie sacrale'],
    intentHints: ['understand_self', 'health_energy'],
    priority: 72,
  },
  {
    key: 'hd_spleen_center',
    science: 'human_design',
    label: 'Centre Spleen (Instinct)',
    keywords: ['spleen hd', 'centre spleen', 'instinct hd', 'spleen center', 'intuition instantanee hd'],
    intentHints: ['understand_self', 'make_decision'],
    priority: 68,
  },
  {
    key: 'hd_root_center',
    science: 'human_design',
    label: 'Centre Racine',
    keywords: ['centre racine hd', 'root center', 'pression racine hd', 'stress hd'],
    intentHints: ['understand_self', 'health_energy'],
    priority: 62,
  },

  // ── PORTES / CANAUX ───────────────────────────────────────────────────────

  {
    key: 'hd_gates',
    science: 'human_design',
    label: 'Portes HD',
    keywords: ['portes hd', 'mes portes', 'porte', 'gates hd', 'porte activee', 'porte consciente', 'porte inconsciente'],
    aliases: ['gates'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 80,
  },
  {
    key: 'hd_gate_meaning',
    science: 'human_design',
    label: 'Signification d\'une porte',
    keywords: ['que signifie la porte', 'porte 1 hd', 'porte 2 hd', 'porte 3 hd', 'porte 10 hd', 'porte 25 hd', 'porte 36 hd'],
    intentHints: ['direct_knowledge'],
    priority: 68,
  },
  {
    key: 'hd_channels',
    science: 'human_design',
    label: 'Canaux HD',
    keywords: ['canaux hd', 'mes canaux', 'canal hd', 'channels hd', 'canal actif', 'canal de'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 80,
  },
  {
    key: 'hd_channel_meaning',
    science: 'human_design',
    label: 'Signification d\'un canal',
    keywords: ['que signifie le canal', 'canal de la force', 'canal de la decouverte'],
    intentHints: ['direct_knowledge'],
    priority: 65,
  },
  {
    key: 'hd_hanging_gates',
    science: 'human_design',
    label: 'Portes pendantes',
    keywords: ['porte pendante', 'portes pendantes', 'hanging gate', 'demi-canal', 'canal incomplet'],
    intentHints: ['understand_self', 'understand_relationship'],
    priority: 65,
  },
  {
    key: 'hd_activation_patterns',
    science: 'human_design',
    label: 'Patterns d activation',
    keywords: ['pattern d activation', 'activation patterns', 'schema d activation hd', 'sequence d activation'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 60,
  },

  // ── LIGNES / PROFIL / CROIX ───────────────────────────────────────────────

  {
    key: 'hd_lines',
    science: 'human_design',
    label: 'Lignes du profil',
    keywords: ['lignes hd', 'ligne 1', 'ligne 2', 'ligne 3', 'ligne 4', 'ligne 5', 'ligne 6', 'investigateur hd', 'hermite hd', 'martyr hd', 'opportuniste hd', 'heraut hd', 'modele de role hd'],
    intentHints: ['understand_self'],
    priority: 72,
  },
  {
    key: 'hd_profile_dynamics',
    science: 'human_design',
    label: 'Dynamiques du profil',
    keywords: ['dynamique du profil hd', 'ligne consciente ligne inconsciente', 'theme de vie hd'],
    intentHints: ['understand_self'],
    priority: 68,
  },
  {
    key: 'hd_incarnation_cross_detail',
    science: 'human_design',
    label: 'Détail croix d\'incarnation',
    keywords: ['detail croix', 'ma croix en detail', 'signification croix hd', 'croix angle droit', 'croix angle gauche', 'croix juxtaposition'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 75,
  },
  {
    key: 'hd_right_angle_cross',
    science: 'human_design',
    label: 'Right Angle Cross',
    keywords: ['right angle cross', 'croix angle droit', 'angle droit hd'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 62,
  },
  {
    key: 'hd_left_angle_cross',
    science: 'human_design',
    label: 'Left Angle Cross',
    keywords: ['left angle cross', 'croix angle gauche', 'angle gauche hd'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 62,
  },
  {
    key: 'hd_juxtaposition_cross',
    science: 'human_design',
    label: 'Juxtaposition Cross',
    keywords: ['juxtaposition cross', 'croix juxtaposition', 'juxtaposition hd'],
    intentHints: ['understand_self', 'spiritual_axis'],
    priority: 62,
  },

  // ── VARIABLES / COGNITION / PHS ───────────────────────────────────────────

  {
    key: 'hd_variables',
    science: 'human_design',
    label: 'Variables HD',
    keywords: ['variables hd', 'fleches hd', 'phs hd', 'primary health system'],
    intentHints: ['understand_self', 'health_energy'],
    priority: 70,
  },
  {
    key: 'hd_arrows',
    science: 'human_design',
    label: 'Flèches HD',
    keywords: ['fleches hd', 'quatre fleches', 'orientation des fleches', 'motivation hd'],
    intentHints: ['understand_self'],
    priority: 68,
  },
  {
    key: 'hd_digestion',
    science: 'human_design',
    label: 'Digestion HD',
    keywords: ['digestion hd', 'comment je mange hd', 'alimentation hd', 'comment je digere'],
    intentHints: ['health_energy'],
    priority: 65,
  },
  {
    key: 'hd_environment',
    science: 'human_design',
    label: 'Environnement HD',
    keywords: ['environnement hd', 'mon environnement', 'ou vivre hd', 'espace de vie hd'],
    intentHints: ['home_space', 'health_energy'],
    priority: 65,
  },
  {
    key: 'hd_perspective',
    science: 'human_design',
    label: 'Perspective HD',
    keywords: ['perspective hd', 'mon angle de vue', 'comment je percois'],
    intentHints: ['understand_self'],
    priority: 60,
  },
  {
    key: 'hd_motivation',
    science: 'human_design',
    label: 'Motivation HD',
    keywords: ['motivation hd', 'ce qui me motive hd', 'peur plaisir esperance desir'],
    intentHints: ['understand_self'],
    priority: 60,
  },
  {
    key: 'hd_cognition',
    science: 'human_design',
    label: 'Cognition HD',
    keywords: ['cognition hd', 'comment j apprends hd', 'sens dominant hd'],
    intentHints: ['understand_self'],
    priority: 60,
  },
  {
    key: 'hd_determination',
    science: 'human_design',
    label: 'Determination HD',
    keywords: ['determination hd', 'ma determination', 'digestion precise hd', 'mode d assimilation hd'],
    intentHints: ['understand_self', 'health_energy'],
    priority: 60,
  },

  // ── RELATIONNEL HD ────────────────────────────────────────────────────────

  {
    key: 'hd_connection_dynamics',
    science: 'human_design',
    label: 'Dynamiques de connexion',
    keywords: ['connexion hd', 'compatibilite hd', 'dynamique couple hd', 'nos charts', 'charts croises hd'],
    intentHints: ['understand_relationship'],
    priority: 82,
  },
  {
    key: 'hd_composite',
    science: 'human_design',
    label: 'Composite HD',
    keywords: ['composite hd', 'chart composite hd', 'design composite', 'bodygraph composite'],
    intentHints: ['understand_relationship'],
    priority: 72,
  },
  {
    key: 'hd_electromagnetic',
    science: 'human_design',
    label: 'Électromagnétique',
    keywords: ['electromagnetique hd', 'electrodes', 'activation electromagnétique'],
    intentHints: ['understand_relationship'],
    priority: 65,
  },
  {
    key: 'hd_compromise',
    science: 'human_design',
    label: 'Compromis et dominance',
    keywords: ['compromis hd', 'dominance hd', 'conflits hd couple'],
    intentHints: ['understand_relationship'],
    priority: 60,
  },
  {
    key: 'hd_friendship',
    science: 'human_design',
    label: 'Amitie HD',
    keywords: ['amitie hd', 'friendship hd', 'dynamique amicale hd', 'compatibilite amicale hd'],
    intentHints: ['understand_relationship'],
    priority: 58,
  },
  {
    key: 'hd_dominance',
    science: 'human_design',
    label: 'Dominance HD',
    keywords: ['dominance hd', 'qui domine dans la relation hd', 'rapport de force hd'],
    intentHints: ['understand_relationship'],
    priority: 58,
  },

  // ── TRANSITS / TEMPS HD ───────────────────────────────────────────────────

  {
    key: 'hd_current_transits',
    science: 'human_design',
    label: 'Transits Human Design actuels',
    keywords: ['transits human design', 'transits hd', 'transits hd actuels', 'energie hd du moment', 'cycle hd actuel'],
    intentHints: ['understand_period', 'timing'],
    priority: 88,
  },
  {
    key: 'hd_current_cycle',
    science: 'human_design',
    label: 'Cycle actuel HD',
    keywords: ['cycle actuel hd', 'cycle en cours hd', 'periode actuelle hd', 'current cycle hd'],
    intentHints: ['understand_period', 'timing'],
    priority: 72,
  },
  {
    key: 'hd_lunar_cycle',
    science: 'human_design',
    label: 'Cycle lunaire HD',
    keywords: ['cycle lunaire hd', 'lune hd', 'cycle 28 jours hd'],
    intentHints: ['timing', 'understand_period'],
    priority: 70,
  },
  {
    key: 'hd_solar_cycle',
    science: 'human_design',
    label: 'Cycle solaire HD',
    keywords: ['cycle solaire hd', 'solar cycle hd', 'cycle du soleil hd'],
    intentHints: ['understand_period', 'timing'],
    priority: 62,
  },
  {
    key: 'hd_saturn_cycle',
    science: 'human_design',
    label: 'Cycle de Saturne HD',
    keywords: ['saturn cycle hd', 'cycle de saturne hd', 'retour de saturne hd'],
    intentHints: ['understand_period', 'timing'],
    priority: 64,
  },
  {
    key: 'hd_uranus_cycle',
    science: 'human_design',
    label: 'Cycle d Uranus HD',
    keywords: ['uranus cycle hd', 'cycle d uranus hd', 'opposition uranus hd'],
    intentHints: ['understand_period'],
    priority: 60,
  },
  {
    key: 'hd_chiron_cycle',
    science: 'human_design',
    label: 'Cycle de Chiron HD',
    keywords: ['chiron cycle hd', 'cycle de chiron hd', 'retour chiron hd'],
    intentHints: ['understand_period', 'spiritual_axis'],
    priority: 60,
  },
  {
    key: 'hd_return_reading',
    science: 'human_design',
    label: 'Lecture de retour HD',
    keywords: ['retour saturne hd', 'retour chiron hd', 'grands cycles hd'],
    intentHints: ['understand_period'],
    priority: 65,
  },

  // ── AVANCÉ HD ─────────────────────────────────────────────────────────────

  {
    key: 'hd_circuitry',
    science: 'human_design',
    label: 'Circuiterie',
    keywords: ['circuiterie hd', 'circuit hd', 'circuit collectif', 'circuit individuel', 'circuit tribal'],
    intentHints: ['understand_self'],
    priority: 62,
  },
  {
    key: 'hd_quarters',
    science: 'human_design',
    label: 'Quartiers',
    keywords: ['quartier hd', 'quartiers hd', 'quarterwise'],
    intentHints: ['understand_self'],
    priority: 55,
  },
  {
    key: 'hd_penta',
    science: 'human_design',
    label: 'Penta',
    keywords: ['penta hd', 'petit groupe hd', 'dynamique penta'],
    intentHints: ['understand_relationship', 'direct_knowledge'],
    priority: 56,
  },
  {
    key: 'hd_bg5',
    science: 'human_design',
    label: 'BG5',
    keywords: ['bg5', 'bg5 business institute', 'human design business'],
    intentHints: ['career_money', 'direct_knowledge'],
    priority: 58,
  },
  {
    key: 'hd_sleep_design',
    science: 'human_design',
    label: 'Sleep Design',
    keywords: ['sleep design', 'sommeil hd', 'dormir seul hd', 'qualite de sommeil hd'],
    intentHints: ['health_energy'],
    priority: 58,
  },
  {
    key: 'hd_parent_child',
    science: 'human_design',
    label: 'Parent / enfant HD',
    keywords: ['parent child hd', 'relation parent enfant hd', 'parent enfant human design'],
    intentHints: ['understand_relationship'],
    priority: 58,
  },
  {
    key: 'hd_business_team',
    science: 'human_design',
    label: 'Equipe / business HD',
    keywords: ['business team hd', 'equipe hd', 'team dynamics hd', 'equipe de travail hd'],
    intentHints: ['career_money', 'understand_relationship'],
    priority: 60,
  },

  // ============================================================
  // ENNÉAGRAMME
  // ============================================================

  // ── BASE ──────────────────────────────────────────────────────────────────

  {
    key: 'ennea_type_core',
    science: 'enneagram',
    label: 'Type ennéagramme (général)',
    keywords: ['enneagramme', 'ennéagramme', 'mon type', 'quel type', 'trouver mon type', 'je suis quel type', 'decouvrir mon type', 'type ennea'],
    intentHints: ['understand_self'],
    priority: 95,
  },
  {
    key: 'ennea_type_1',
    science: 'enneagram',
    label: 'Type 1 — Le Réformateur',
    keywords: ['type 1 enneagramme', 'ennea type 1', 'reformateur', 'perfectionniste enneagramme', 'rigidite type 1'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },
  {
    key: 'ennea_type_2',
    science: 'enneagram',
    label: 'Type 2 — L\'Aidant',
    keywords: ['type 2 enneagramme', 'ennea type 2', 'aidant enneagramme', 'besoin d etre aime', 'type 2'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },
  {
    key: 'ennea_type_3',
    science: 'enneagram',
    label: 'Type 3 — Le Battant',
    keywords: ['type 3 enneagramme', 'ennea type 3', 'battant', 'performeur enneagramme'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },
  {
    key: 'ennea_type_4',
    science: 'enneagram',
    label: 'Type 4 — L\'Individualiste',
    keywords: ['type 4', 'type 4 enneagramme', 'ennea type 4', 'individualiste', 'romantique', 'unique type 4'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },
  {
    key: 'ennea_type_5',
    science: 'enneagram',
    label: 'Type 5 — L\'Observateur',
    keywords: ['type 5 enneagramme', 'ennea type 5', 'observateur', 'retrait type 5', 'avare d energie'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },
  {
    key: 'ennea_type_6',
    science: 'enneagram',
    label: 'Type 6 — Le Loyaliste',
    keywords: ['type 6', 'type 6 enneagramme', 'ennea type 6', 'loyaliste', 'anxieux type 6', 'contre-phobique'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },
  {
    key: 'ennea_type_7',
    science: 'enneagram',
    label: 'Type 7 — L\'Épicurien',
    keywords: ['type 7 enneagramme', 'ennea type 7', 'epicurien', 'enthousiaste', 'dispersé type 7'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },
  {
    key: 'ennea_type_8',
    science: 'enneagram',
    label: 'Type 8 — Le Challenger',
    keywords: ['type 8', 'type 8 enneagramme', 'ennea type 8', 'challenger', 'assertif type 8', 'dominant type 8'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },
  {
    key: 'ennea_type_9',
    science: 'enneagram',
    label: 'Type 9 — Le Médiateur',
    keywords: ['type 9 enneagramme', 'ennea type 9', 'mediateur enneagramme', 'pacificateur', 'paresseux type 9'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 70,
  },

  // ── STRUCTURE ─────────────────────────────────────────────────────────────

  {
    key: 'ennea_wings',
    science: 'enneagram',
    label: 'Ailes',
    keywords: ['aile', 'ailes', 'wing', 'wings', 'mon aile', 'aile 1', 'aile 2', 'aile 3', 'aile 4', 'aile 5', 'aile 6', 'aile 7', 'aile 8', 'aile 9'],
    aliases: ['wing'],
    intentHints: ['understand_self'],
    priority: 85,
  },
  {
    key: 'ennea_instincts',
    science: 'enneagram',
    label: 'Sous-types / Instincts',
    keywords: ['sous-type', 'soustype', 'instinct', 'instinct dominant', 'instinct sexuel', 'sx', 'sp', 'so', 'social', 'autoconservation', 'instinct de conservation', 'instinct social', 'instinct sexuel ennea'],
    intentHints: ['understand_self'],
    priority: 82,
  },
  {
    key: 'ennea_tritype',
    science: 'enneagram',
    label: 'Tritype',
    keywords: ['tritype', 'triple type', 'trois centres'],
    intentHints: ['understand_self'],
    priority: 75,
  },
  {
    key: 'ennea_centers_of_intelligence',
    science: 'enneagram',
    label: 'Centres d\'intelligence',
    keywords: ['centre de l instinct', 'centre du coeur', 'centre du mental', 'triade tete', 'triade coeur', 'triade corps', 'centre triade'],
    intentHints: ['understand_self'],
    priority: 72,
  },
  {
    key: 'ennea_harmonic_groups',
    science: 'enneagram',
    label: 'Groupes harmoniques',
    keywords: ['groupe harmonique', 'harmonic group', 'competence', 'positivite', 'reactif'],
    intentHints: ['understand_self'],
    priority: 60,
  },
  {
    key: 'ennea_hornevian_groups',
    science: 'enneagram',
    label: 'Groupes horneviens',
    keywords: ['groupe hornevien', 'hornevian', 'assertif', 'retrait', 'conformiste', 'replie'],
    intentHints: ['understand_self'],
    priority: 58,
  },
  {
    key: 'ennea_object_relations',
    science: 'enneagram',
    label: 'Relations d objet',
    keywords: ['object relations', 'relation d objet', 'frustration ennea', 'rejet ennea', 'attachement ennea'],
    intentHints: ['understand_self', 'understand_relationship'],
    priority: 58,
  },

  // ── DYNAMIQUE ─────────────────────────────────────────────────────────────

  {
    key: 'ennea_integration',
    science: 'enneagram',
    label: 'Chemin d\'intégration',
    keywords: ['integration', 'chemin d integration', 'croissance enneagramme', 'aller vers', 'stress positif ennea'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 78,
  },
  {
    key: 'ennea_disintegration',
    science: 'enneagram',
    label: 'Chemin de désintégration',
    keywords: ['desintegration', 'chemin de desintegration', 'en stress', 'aller vers le bas', 'regression ennea', 'desintegration du type', 'sous stress'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 80,
  },
  {
    key: 'ennea_levels_of_health',
    science: 'enneagram',
    label: 'Niveaux de développement',
    keywords: ['niveau de sante', 'niveau de developpement', 'niveaux ennea', 'sain moyen malsain'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 75,
  },
  {
    key: 'ennea_defense_mechanisms',
    science: 'enneagram',
    label: 'Mécanismes de défense',
    keywords: ['mecanisme de defense', 'defense ennea', 'protection psychologique', 'reactance ennea'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 72,
  },
  {
    key: 'ennea_core_fear',
    science: 'enneagram',
    label: 'Peur centrale',
    keywords: ['peur centrale', 'peur profonde', 'peur fondamentale', 'ma peur ennea'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 82,
  },
  {
    key: 'ennea_core_desire',
    science: 'enneagram',
    label: 'Désir central',
    keywords: ['desir central', 'desir profond', 'besoin fondamental ennea', 'motivation centrale'],
    intentHints: ['understand_self'],
    priority: 78,
  },
  {
    key: 'ennea_childhood_wound',
    science: 'enneagram',
    label: 'Blessure d\'enfance',
    keywords: ['blessure d enfance ennea', 'message de l enfance', 'croyance enfance ennea', 'schéma enfantin'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 72,
  },
  {
    key: 'ennea_blind_spots',
    science: 'enneagram',
    label: 'Angles morts',
    keywords: ['angle mort ennea', 'aveugle ennea', 'ce que je ne vois pas', 'blind spot'],
    intentHints: ['understand_self', 'understand_block'],
    priority: 70,
  },

  // ── RELATIONNEL ENNEA ────────────────────────────────────────────────────

  {
    key: 'ennea_relationship_dynamics',
    science: 'enneagram',
    label: 'Dynamiques relationnelles',
    keywords: ['relation ennea', 'couple ennea', 'dynamique couple enneagramme', 'mon style en couple', 'compatibilite ennea'],
    intentHints: ['understand_relationship'],
    priority: 82,
  },
  {
    key: 'ennea_couple_compatibility',
    science: 'enneagram',
    label: 'Compatibilité de couple',
    keywords: ['compatibilite couple ennea', 'quel type avec quel type', 'tension couple enneagramme'],
    intentHints: ['understand_relationship'],
    priority: 75,
  },
  {
    key: 'ennea_team_dynamics',
    science: 'enneagram',
    label: 'Dynamiques d\'équipe',
    keywords: ['equipe ennea', 'travail en equipe enneagramme', 'conflit equipe ennea'],
    intentHints: ['career_money', 'understand_relationship'],
    priority: 68,
  },
  {
    key: 'ennea_conflict_patterns',
    science: 'enneagram',
    label: 'Schémas de conflit',
    keywords: ['conflit ennea', 'patterns de conflit', 'mode d opposition', 'comment je gere le conflit'],
    intentHints: ['understand_relationship', 'understand_block'],
    priority: 72,
  },

  // ── MATÉRIEL / PRO ────────────────────────────────────────────────────────

  {
    key: 'ennea_work_style',
    science: 'enneagram',
    label: 'Style de travail',
    keywords: ['style de travail ennea', 'travail enneagramme', 'comment je travaille', 'productivite ennea'],
    intentHints: ['career_money'],
    priority: 72,
  },
  {
    key: 'ennea_leadership_style',
    science: 'enneagram',
    label: 'Style de leadership',
    keywords: ['leadership ennea', 'style de leadership', 'manager enneagramme', 'comment je dirige'],
    intentHints: ['career_money'],
    priority: 68,
  },
  {
    key: 'ennea_money_patterns',
    science: 'enneagram',
    label: 'Patterns argent',
    keywords: ['argent ennea', 'rapport a l argent enneagramme', 'patterns financiers ennea'],
    intentHints: ['career_money'],
    priority: 65,
  },
  {
    key: 'ennea_decision_style',
    science: 'enneagram',
    label: 'Style de décision',
    keywords: ['comment je decide ennea', 'decision enneagramme', 'style de decision ennea'],
    intentHints: ['make_decision'],
    priority: 72,
  },

  // ── SPIRITUEL ─────────────────────────────────────────────────────────────

  {
    key: 'ennea_growth_path',
    science: 'enneagram',
    label: 'Chemin de croissance',
    keywords: ['chemin de croissance ennea', 'evolution enneagramme', 'devenir meilleur version', 'grandir ennea'],
    intentHints: ['spiritual_axis', 'understand_self'],
    priority: 75,
  },
  {
    key: 'ennea_shadow_work',
    science: 'enneagram',
    label: 'Travail sur l\'ombre',
    keywords: ['ombre ennea', 'travail de l ombre', 'shadow work enneagramme', 'part sombre ennea'],
    intentHints: ['spiritual_axis', 'understand_block'],
    priority: 72,
  },
  {
    key: 'ennea_presence_axis',
    science: 'enneagram',
    label: 'Axe de présence',
    keywords: ['presence ennea', 'conscience ennea', 'eveil enneagramme', 'essence ennea'],
    intentHints: ['spiritual_axis'],
    priority: 65,
  },

  // ============================================================
  // KUA
  // ============================================================

  // ── BASE ──────────────────────────────────────────────────────────────────

  {
    key: 'kua_number',
    science: 'kua',
    label: 'Nombre Kua',
    keywords: ['nombre kua', 'mon kua', 'kua', 'numero kua', 'calcul kua'],
    intentHints: ['understand_self', 'direct_knowledge'],
    priority: 95,
  },
  {
    key: 'kua_group',
    science: 'kua',
    label: 'Groupe Est / Ouest',
    keywords: ['groupe est', 'groupe ouest', 'groupe kua', 'est ouest feng shui'],
    intentHints: ['understand_self'],
    priority: 72,
  },
  {
    key: 'kua_element',
    science: 'kua',
    label: 'Élément Kua',
    keywords: ['element kua', 'element feng shui', 'mon element feng shui', 'bois feu terre metal eau kua'],
    intentHints: ['understand_self'],
    priority: 68,
  },
  {
    key: 'kua_profile',
    science: 'kua',
    label: 'Profil Kua complet',
    keywords: ['profil kua', 'lecture kua', 'mon kua complet'],
    intentHints: ['understand_self'],
    priority: 82,
  },

  // ── DIRECTIONS ────────────────────────────────────────────────────────────

  {
    key: 'kua_favorable_directions',
    science: 'kua',
    label: 'Directions favorables',
    keywords: ['direction favorable', 'directions favorables', 'mes directions', 'orientation favorable', 'bonne direction', 'quelle direction'],
    intentHints: ['home_space', 'make_decision'],
    priority: 92,
  },
  {
    key: 'kua_unfavorable_directions',
    science: 'kua',
    label: 'Directions défavorables',
    keywords: ['direction defavorable', 'mauvaise direction', 'direction a eviter', 'orientation a eviter'],
    intentHints: ['home_space'],
    priority: 80,
  },
  {
    key: 'kua_sheng_chi',
    science: 'kua',
    label: 'Sheng Chi — Prospérité',
    keywords: ['sheng chi', 'direction prosperite', 'direction croissance'],
    intentHints: ['career_money', 'home_space'],
    priority: 78,
  },
  {
    key: 'kua_tien_yi',
    science: 'kua',
    label: 'Tien Yi — Santé',
    keywords: ['tien yi', 'direction sante kua', 'doctor direction'],
    intentHints: ['health_energy', 'home_space'],
    priority: 75,
  },
  {
    key: 'kua_nien_yen',
    science: 'kua',
    label: 'Nien Yen — Relation',
    keywords: ['nien yen', 'direction relation kua', 'romance direction'],
    intentHints: ['understand_relationship', 'home_space'],
    priority: 75,
  },
  {
    key: 'kua_fu_wei',
    science: 'kua',
    label: 'Fu Wei — Croissance personnelle',
    keywords: ['fu wei', 'direction croissance personnelle', 'direction calme kua'],
    intentHints: ['understand_self', 'home_space'],
    priority: 72,
  },
  {
    key: 'kua_ho_hai',
    science: 'kua',
    label: 'Ho Hai — Accidents',
    keywords: ['ho hai', 'direction accidents', 'direction fatalite'],
    intentHints: ['home_space'],
    priority: 65,
  },
  {
    key: 'kua_wu_kuei',
    science: 'kua',
    label: 'Wu Kuei — Cinq Fantômes',
    keywords: ['wu kuei', 'cinq fantomes', 'direction conflit'],
    intentHints: ['home_space'],
    priority: 62,
  },
  {
    key: 'kua_liu_sha',
    science: 'kua',
    label: 'Liu Sha — Six Tueurs',
    keywords: ['liu sha', 'six tueurs', 'direction perte'],
    intentHints: ['home_space'],
    priority: 62,
  },
  {
    key: 'kua_chueh_ming',
    science: 'kua',
    label: 'Chueh Ming — Total Désastre',
    keywords: ['chueh ming', 'total desastre', 'direction catastrophe'],
    intentHints: ['home_space'],
    priority: 60,
  },

  // ── HABITAT / ESPACE ──────────────────────────────────────────────────────

  {
    key: 'kua_bed_orientation',
    science: 'kua',
    label: 'Orientation du lit',
    keywords: ['orientation lit', 'orientation du lit', 'orientation de mon lit', 'ou dormir', 'direction du lit', 'sens du lit', 'tete du lit', 'position lit kua'],
    intentHints: ['home_space', 'health_energy'],
    priority: 88,
  },
  {
    key: 'kua_desk_orientation',
    science: 'kua',
    label: 'Orientation du bureau',
    keywords: ['orientation bureau', 'orientation du bureau', 'orientation de mon bureau', 'ou placer mon bureau', 'sens du bureau', 'direction bureau', 'position bureau kua'],
    intentHints: ['home_space', 'career_money'],
    priority: 85,
  },
  {
    key: 'kua_front_door_orientation',
    science: 'kua',
    label: 'Orientation porte d\'entrée',
    keywords: ['porte d entree orientation', 'sens porte d entree', 'direction porte', 'quelle porte kua'],
    intentHints: ['home_space'],
    priority: 80,
  },
  {
    key: 'kua_home_layout',
    science: 'kua',
    label: 'Agencement de la maison',
    keywords: ['agencement maison kua', 'plan maison feng shui', 'organisation espace kua'],
    intentHints: ['home_space'],
    priority: 75,
  },
  {
    key: 'kua_room_usage',
    science: 'kua',
    label: 'Usage des pièces',
    keywords: ['quelle piece pour', 'piece kua', 'usage des pieces', 'ou mettre ma chambre'],
    intentHints: ['home_space'],
    priority: 72,
  },
  {
    key: 'kua_sleep_axis',
    science: 'kua',
    label: 'Axe sommeil',
    keywords: ['axe sommeil kua', 'dormir bien kua', 'recuperation kua'],
    intentHints: ['home_space', 'health_energy'],
    priority: 78,
  },
  {
    key: 'kua_work_axis',
    science: 'kua',
    label: 'Axe travail',
    keywords: ['axe travail kua', 'travailler mieux kua', 'productivite kua', 'concentration kua'],
    intentHints: ['career_money', 'home_space'],
    priority: 78,
  },
  {
    key: 'kua_home_space_alignment',
    science: 'kua',
    label: 'Alignement espace de vie',
    keywords: ['aligner mon espace', 'espace aligne kua', 'harmonie maison kua', 'equilibre maison kua'],
    intentHints: ['home_space'],
    priority: 80,
  },

  // ── RELATIONNEL KUA ───────────────────────────────────────────────────────

  {
    key: 'kua_relationship_match',
    science: 'kua',
    label: 'Compatibilité Kua',
    keywords: ['compatibilite kua', 'kua couple', 'meme groupe kua', 'groupe compatible kua'],
    intentHints: ['understand_relationship'],
    priority: 75,
  },
  {
    key: 'kua_family_harmony',
    science: 'kua',
    label: 'Harmonie familiale',
    keywords: ['harmonie famille kua', 'kua famille', 'feng shui famille'],
    intentHints: ['understand_relationship', 'home_space'],
    priority: 68,
  },

  // ── TEMPS / DIRECTION DE VIE ──────────────────────────────────────────────

  {
    key: 'kua_annual_influence',
    science: 'kua',
    label: 'Influence annuelle',
    keywords: ['annee kua', 'influence annuelle kua', 'energie annuelle feng shui', 'annee feng shui'],
    intentHints: ['understand_period', 'timing'],
    priority: 72,
  },
  {
    key: 'kua_timing_support',
    science: 'kua',
    label: 'Support timing Kua',
    keywords: ['timing kua', 'bon moment kua', 'quand agir kua'],
    intentHints: ['timing'],
    priority: 70,
  },
  {
    key: 'kua_decision_direction',
    science: 'kua',
    label: 'Direction de décision',
    keywords: ['direction pour decider', 'se tourner vers kua', 'quelle direction quand je decide'],
    intentHints: ['make_decision', 'home_space'],
    priority: 75,
  },

  // ── SPATIAL ÉTENDU KUA ────────────────────────────────────────────────────

  {
    key: 'kua_feng_shui_link',
    science: 'kua',
    label: 'Lien Feng Shui',
    keywords: ['feng shui', 'feng shui perso', 'feng shui personnel', 'feng shui kua'],
    aliases: ['feng shui perso'],
    intentHints: ['home_space'],
    priority: 80,
  },
  {
    key: 'kua_move_location',
    science: 'kua',
    label: 'Déménagement / lieu de vie',
    keywords: ['ou vivre kua', 'demenager kua', 'quelle ville kua', 'quelle maison kua'],
    intentHints: ['home_space', 'make_decision'],
    priority: 72,
  },
  {
    key: 'kua_geo_alignment',
    science: 'kua',
    label: 'Alignement géographique',
    keywords: ['alignement geographique kua', 'pays kua', 'continent kua'],
    intentHints: ['home_space'],
    priority: 60,
  },

  // ============================================================
  // FUSION
  // ============================================================

  {
    key: 'fusion_general',
    science: 'fusion',
    label: 'Fusion générale',
    keywords: ['que se passe dans ma vie', 'pourquoi ca bloque', 'que dois-je faire', 'que faire maintenant', 'comprendre ma situation', 'ma vie', 'lecture generale', 'lecture globale'],
    intentHints: ['general', 'understand_block'],
    priority: 50,
  },
  {
    key: 'fusion_relationships',
    science: 'fusion',
    label: 'Fusion — Relations',
    keywords: ['ma relation', 'mon couple', 'mes relations', 'comprendre mes relations', 'amour fusion', 'vie amoureuse'],
    intentHints: ['understand_relationship'],
    priority: 75,
  },
  {
    key: 'fusion_decision',
    science: 'fusion',
    label: 'Fusion — Décision',
    keywords: ['quelle decision', 'je ne sais pas quoi choisir', 'choisir entre', 'hésiter', 'je dois decider', 'aide a la decision', 'dois-je', 'direction prendre', 'quelle direction prendre'],
    intentHints: ['make_decision'],
    priority: 80,
  },
  {
    key: 'fusion_timing',
    science: 'fusion',
    label: 'Fusion — Timing',
    keywords: ['quel est le bon moment', 'quand agir', 'est-ce le bon moment', 'timing general', 'maintenant ou attendre'],
    intentHints: ['timing'],
    priority: 82,
  },
  {
    key: 'fusion_career_money',
    science: 'fusion',
    label: 'Fusion — Carrière & Argent',
    keywords: [
      'ma carriere',
      'mon travail',
      'mon argent',
      'mes finances',
      'vie professionnelle',
      'trouver ma voie',
      'changer de metier',
      'evoluer pro',
      'quel metier est fait pour moi',
      'quel travail est fait pour moi',
      'quel metier me correspond',
      'pour quel metier suis je fait',
      'quelle carriere me correspond',
      'quelle voie pro me correspond',
      'orientation professionnelle',
      'voie professionnelle',
      'dans quoi suis je bon au travail',
      'vocation professionnelle',
    ],
    intentHints: ['career_money'],
    priority: 78,
  },
  {
    key: 'fusion_energy_state',
    science: 'fusion',
    label: 'Fusion — Énergie & État',
    keywords: ['mon energie', 'comment je me sens', 'fatigue profonde', 'etat energetique', 'vitre basse', 'je suis a plat', 'epuisement'],
    intentHints: ['health_energy', 'understand_period'],
    priority: 75,
  },
  {
    key: 'fusion_spiritual_axis',
    science: 'fusion',
    label: 'Fusion — Axe spirituel',
    keywords: ['mon chemin spirituel', 'axe spirituel', 'mission de vie', 'evolution spirituelle', 'sens de ma vie', 'pourquoi je suis la'],
    intentHints: ['spiritual_axis'],
    priority: 72,
  },
  {
    key: 'fusion_life_situation',
    science: 'fusion',
    label: 'Fusion — Situation de vie',
    keywords: ['ma situation', 'comment comprendre cette situation', 'qu est-ce que je traverse', 'ce que je vis', 'analyser ma situation'],
    intentHints: ['general', 'understand_period'],
    priority: 70,
  },
  {
    key: 'fusion_blockage',
    science: 'fusion',
    label: 'Fusion — Blocage',
    keywords: ['je bloque', 'je stagne', 'blocage', 'je n avance pas', 'rien ne change', 'pourquoi ca ne marche pas', 'je tourne en rond'],
    intentHints: ['understand_block'],
    priority: 80,
  },
  {
    key: 'fusion_transition_phase',
    science: 'fusion',
    label: 'Fusion — Phase de transition',
    keywords: ['en transition', 'periode de changement', 'nouveau depart', 'tournant de vie', 'phase de transformation', 'tout change'],
    intentHints: ['understand_period', 'timing'],
    priority: 78,
  },
]

export const SCIENCE_TAXONOMY_BY_SCIENCE: Record<Science, ScienceSubCategory[]> = {
  astro: SCIENCE_TAXONOMY.filter((category) => category.science === 'astro'),
  numerology: SCIENCE_TAXONOMY.filter((category) => category.science === 'numerology'),
  human_design: SCIENCE_TAXONOMY.filter((category) => category.science === 'human_design'),
  enneagram: SCIENCE_TAXONOMY.filter((category) => category.science === 'enneagram'),
  kua: SCIENCE_TAXONOMY.filter((category) => category.science === 'kua'),
  fusion: SCIENCE_TAXONOMY.filter((category) => category.science === 'fusion'),
}

export const SCIENCE_SUBCATEGORY_INDEX: Record<string, ScienceSubCategory> = Object.fromEntries(
  SCIENCE_TAXONOMY.map((category) => [category.key, category]),
) as Record<string, ScienceSubCategory>
